show_entries:
    path: /entries
    controller: App\Blog\Application\Controller\EntryController:showAll
    
show_entry: 
    path: /entry/{id}
    controller: App\Blog\Application\Controller\EntryController:showByID
    
welcome:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: '@blog/static/welcome.html.twig'
    