services:
    App\Blog\Infrastructure\Repository\InMemoryEntryRepository: ~
    App\Blog\Infrastructure\Repository\DoctrineEntryRepository: ~
    App\Blog\Domain\Repository\IEntryRepository: '@App\Blog\Infrastructure\Repository\DoctrineEntryRepository'
        