services:
    App\Blog\Infraestructure\Repository\InMemoryEntryRepository: ~
    App\Blog\Infraestructure\Repository\IEntryRepository: '@App\Blog\Infraestructure\Repository\InMemoryEntryRepository'
        